### PR TITLE
Fixed React undefined error

### PR DESCRIPTION
**Pull request by aditya5076**
This repo exists only to provide example code for the [Build a Shopify app with Node and React](https://developers.shopify.com/tutorials/build-a-shopify-app-with-node-and-react/) tutorial. Thank you for taking the time to submit a pull request, but we are not accepting contributions at this time, and all external PRs will be closed without merging.

### CODE REVIEW

**Comment by paulomarg** [comment]
Hi @aditya5076, thank you for contributing! In our tests we haven't had any issue like this one, please make sure you've followed [the usage instructions](https://github.com/Shopify/shopify-demo-app-node-react#using-demo-app) to see if that fixes the issue.

I'm closing this PR since this looks more like a setup issue than a code one.

**Comment by mathewgrabau** [comment]
Hello @paulomarg - do you have any insight as to the setup issue that may have caused this? I hit the same issue and am wondering what the correct (setup) resolution is (not the code issue - this fix resolved the issue for me).

**Comment by paulomarg** [comment]
It's hard to say exactly what could have caused this, but what I meant by `setup` was setting things up as per the tutorial (not the best wording, apologies), perhaps you skipped some step where React would be imported?

I'm actually going over this tutorial at the moment, and will keep in mind to double check this step to ensure it isn't actually wrong!

**Comment by paulomarg** [comment]
Update: it seems the tutorial is actually out of date and this PR is the right solution. I will make sure it is updated. Thank you for raising it again.

**Comment by mathewgrabau** [comment]
Thanks @paulomarg - I appreciate the quick response on it. Overall, I find the docs (and this tutorial) extremely good. My regards to you and your colleagues for the delightful experience.

**Review by coder-examples — COMMENTED** [review]
Correct Solution

**Pull request closed without merging**
