### PR TITLE
Update README for Shopify Node / React demo app

### PR DESCRIPTION
**Pull request by mcvinci**
## This PR: 
- Updates the README to align with the new apps getting started experience on Shopify.dev
- Fixes an issue reported via email:
    Screen Shot 2021-07-10 at 11 36 49 AM
    
### Tophatted

screencapture-github-Shopify-shopify-demo-app-node-react-blob-33432e6af25dee24db1b427b8954194d44dcede7-README-md-2021-07-10-11_35_09

### CODE REVIEW

**Comment by joshbedo** [comment]
Does this still work anymore? I had an app running until just yesterday now authentication is broke and it keeps saying the url isnt whitelisted when it is. When I look at the redirect url it shows it like this `https://<shopify-store>.com/admin/oauth/authorize?state=162606223489200&scope=read_products%2C%20write_products&client_id=7df8fdd2d22aeec22b724fcaab6fb17e&redirect_uri=https%3A%2F%2F3fbe6f48998a.ngrok.io%2Fauth%2Fcallback&grant_options%5B%5D=per-user`

**Comment by paulomarg** [comment]
This app has actually been deprecated in favour of https://github.com/Shopify/shopify-app-node, but this is a good reminder that we need to mark it as such!

**Review by paulomarg — APPROVED** [review]
Thank you for this! 🚀

**Pull request merged**
