### PR TITLE
without import 'isomorphic-fetch' app does not compile

### PR DESCRIPTION
**Pull request by alsguimaraes**
added import 'isomorphic-fetch' to pages/_app.js.
without this import the app failes to compile.

### CODE REVIEW

**Comment by katiedavis** [comment]
Isomorphic fetch is added at the[ entry point of server.js](https://github.com/Shopify/shopify-demo-app-node-react/blob/master/server.js#L1), it shouldn't be needed on the client side. 

I've never seen this as an issue within the app, so we'd need to take a look to see why this is an issue for @alsguimaraes.

Also, it's lovely you put in a pr @alsguimaraes, but we will need to update a couple repos in a few different places, as well as branches within this PR, that's why we're not accepting external pull requests at this time!

**Comment by markiiikram** [comment]
I'll test the app, and will give you an answer by EOD.

**Comment by markiiikram** [comment]
I was able to build the app from the instructions on https://developers.shopify.com/tutorials/build-a-shopify-app-with-node-and-react without problem. @alsguimaraes were you using a particular starter branch?

**Comment by alsguimaraes** [comment]
@markiiikram , the problem was on the master branch.
If I am not mistaken, you can verify the error by running "npm run build".

**Comment by markiiikram** [comment]
Thanks @alsguimaraes! Sounds good, all ask the team.

**Pull request closed without merging**
